// Generated by `npm run build:kiln-core` from kiln-planner-to-be (src/domain, src/adapters).
// Do not edit here. Copy to kiln-load-planner-web/core/kiln-core.js. See docs/adr/0003.
(()=>{
"use strict";
const modules=Object.create(null);
// src/domain/shared.js
modules["src/domain/shared.js"]=(()=>{
class DomainError extends Error {
  constructor(code, message) { super(message); this.name = 'DomainError'; this.code = code; }
}
function ensure(condition, code, message = code) {
  if (!condition) throw new DomainError(code, message);
}
function text(value, field = 'value') {
  ensure(typeof value === 'string' && value.trim().length > 0, 'REQUIRED_TEXT', field);
  return value;
}
function id(value) { return text(value, 'stable id'); }
// Supply an opaque-token generator from the host (e.g. UUID); tests supply a sequence.
// Call once on creation and retain the returned ID on every subsequent revision.
function createIdFactory(nextToken) {
  ensure(typeof nextToken === 'function', 'ID_GENERATOR_REQUIRED');
  const issued = new Set();
  return kind => {
    const result = `${text(kind)}:${id(nextToken())}`;
    ensure(!issued.has(result), 'DUPLICATE_ID');
    issued.add(result);
    return result;
  };
}
function number(value, field, minimum = 0) {
  ensure(typeof value === 'number' && Number.isFinite(value) && value >= minimum, 'INVALID_NUMBER', field);
  return value;
}
function quantity(value) {
  number(value, 'board quantity');
  ensure(Number.isSafeInteger(value), 'INVALID_QUANTITY');
  return value;
}
function boardLength(value) {
  number(value, 'length in feet'); ensure(value > 0, 'INVALID_LENGTH'); return value;
}
function nominalDimensions({ thicknessIn, widthIn }) {
  ensure(number(thicknessIn, 'nominal thickness') > 0 && number(widthIn, 'nominal width') > 0, 'INVALID_DIMENSIONS');
  return immutable({ thicknessIn, widthIn });
}
function boardFeet(dimensions, lengthFt, boards) {
  const nominal = nominalDimensions(dimensions);
  return nominal.thicknessIn * nominal.widthIn * boardLength(lengthFt) * quantity(boards) / 12;
}
function oneOf(value, allowed, field) {
  ensure(allowed.includes(value), 'INVALID_ENUM', field); return value;
}
function uniqueIds(items) {
  const ids = items.map(item => id(item.id));
  ensure(new Set(ids).size === ids.length, 'DUPLICATE_ID');
}
// Canonical records are detached, deeply frozen JSON data; no mutable class instances.
function immutable(value) {
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return value;
  if (typeof value === 'number') { ensure(Number.isFinite(value), 'NONFINITE_DATA'); return value; }
  if (Array.isArray(value)) return Object.freeze(value.map(immutable));
  ensure(value && typeof value === 'object' && Object.getPrototypeOf(value) === Object.prototype, 'NON_DATA_VALUE');
  return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, immutable(item)])));
}
function entity(value, type) {
  ensure(value?.entityType === type, 'WRONG_ENTITY_TYPE', type);
  id(value.id); return value;
}
function sameOrganization(...values) {
  values.forEach(value => id(value.organizationId));
  ensure(values.every(value => value.organizationId === values[0].organizationId), 'ORGANIZATION_MISMATCH');
}
function owned(type, input, parent, fields) {
  const organizationId = parent.entityType === 'Organization' ? parent.id : parent.organizationId;
  id(organizationId);
  if (input.organizationId !== undefined) ensure(input.organizationId === organizationId, 'ORGANIZATION_MISMATCH');
  return immutable({ entityType:type, id:id(input.id), organizationId, ...fields });
}
function quantities(entries) {
  const result = entries.map(({ lengthFt, quantity: count }) => ({ lengthFt:boardLength(lengthFt), quantity:quantity(count) }));
  ensure(new Set(result.map(item => item.lengthFt)).size === result.length, 'DUPLICATE_LENGTH');
  return immutable(result);
}
function sourceReference(source) {
  text(source?.type, 'source type');
  return immutable({ type:source.type, id:source.id == null ? null : id(source.id), reference:source.reference ?? null });
}

return {DomainError,ensure,text,id,createIdFactory,number,quantity,boardLength,nominalDimensions,boardFeet,oneOf,uniqueIds,immutable,entity,sameOrganization,owned,quantities,sourceReference};
})();

// src/domain/order-balance.js
modules["src/domain/order-balance.js"]=(()=>{
// Order balance: one pure calculation from recorded facts to every figure the
// operator relies on. Each quantity is counted exactly once; any record that
// would count boards twice or draw more than exists is rejected, never clamped.
const { DomainError, ensure, id, text, quantity, boardLength, nominalDimensions, immutable }=modules["src/domain/shared.js"];

const CYCLE_STATUSES = ['planned', 'in-progress', 'completed'];
const EPSILON = 1e-9;

function addLines(target, entries, field) {
  for (const entry of entries ?? []) {
    const length = boardLength(entry.lengthFt);
    const row = target.get(length) ?? {};
    row[field] = (row[field] ?? 0) + quantity(entry.quantity);
    target.set(length, row);
  }
}
function add(target, length, field, count) {
  const row = target.get(length) ?? {};
  row[field] = (row[field] ?? 0) + count;
  target.set(length, row);
}
function unique(items, key, code) {
  const seen = new Set();
  for (const item of items) {
    const value = key(item);
    if (seen.has(value)) throw new DomainError(code, `${code}: ${value}`);
    seen.add(value);
  }
}
const sum = (rows, field) => rows.reduce((total, row) => total + row[field], 0);
const linearFt = (rows, field) => rows.reduce((total, row) => total + row.lengthFt * row[field], 0);

/**
 * input.receipts   [{ id, lines:[{lengthFt, quantity}] }] raw boards received for the order
 * input.cycles     [{ id, number, status, lines }] planned / in-progress quantities, or ACTUAL output when completed
 * input.recoveries [{ id, sourceLengthFt, quantity, piecesFt:[...] }] each source board cut into piecesFt
 * input.tags       [{ id, label, lines }]   input.tests [{ id, lines }]
 * input.maxCycles  optional limit on cycles for this order
 * input.nominal    { thicknessIn, widthIn } for board feet
 */
function computeOrderBalance(input) {
  id(input.orderId);
  const receipts = input.receipts ?? [];
  const cycles = input.cycles ?? [];
  const recoveries = input.recoveries ?? [];
  const tags = input.tags ?? [];
  const tests = input.tests ?? [];

  // No duplicates: every fact has one identity, cycle numbers and TAG labels are unique.
  for (const [items, name] of [[receipts, 'receipt'], [cycles, 'cycle'], [recoveries, 'recovery'], [tags, 'tag'], [tests, 'test']]) {
    items.forEach(item => id(item.id));
    unique(items, item => item.id, 'DUPLICATE_ID');
  }
  unique(cycles, cycle => quantity(cycle.number), 'DUPLICATE_CYCLE_NUMBER');
  unique(tags, tag => text(tag.label).trim().toLowerCase(), 'DUPLICATE_TAG_LABEL');
  if (input.maxCycles != null) ensure(cycles.length <= quantity(input.maxCycles), 'CYCLE_LIMIT_EXCEEDED');

  const raw = new Map();
  receipts.forEach(receipt => addLines(raw, receipt.lines, 'input'));
  for (const cycle of cycles) {
    const status = cycle.status;
    ensure(CYCLE_STATUSES.includes(status), 'INVALID_ENUM', 'cycle status');
    addLines(raw, cycle.lines, status === 'completed' ? 'completed' : status === 'in-progress' ? 'inProgress' : 'planned');
  }

  const finished = new Map();
  cycles.filter(cycle => cycle.status === 'completed').forEach(cycle => addLines(finished, cycle.lines, 'kilnOutput'));
  const recoverySummaries = recoveries.map(recovery => {
    const source = boardLength(recovery.sourceLengthFt);
    const boards = quantity(recovery.quantity);
    ensure(boards > 0, 'EMPTY_RECOVERY');
    const pieces = (recovery.piecesFt ?? []).map(boardLength);
    ensure(pieces.length > 0 && pieces.every(piece => piece < source), 'INVALID_RECOVERY_OUTPUT');
    const usedPerBoard = pieces.reduce((total, piece) => total + piece, 0);
    ensure(usedPerBoard <= source + EPSILON, 'RECOVERY_LONGER_THAN_SOURCE');
    add(finished, source, 'recoveryIn', boards);
    pieces.forEach(piece => add(finished, piece, 'recoveryOut', boards));
    return { id: recovery.id, sourceLengthFt: source, boards, piecesFt: pieces,
      usefulFt: usedPerBoard * boards, removedFt: (source - usedPerBoard) * boards };
  });
  tags.forEach(tag => {
    ensure((tag.lines ?? []).some(line => quantity(line.quantity) > 0), 'EMPTY_TAG');
    addLines(finished, tag.lines, 'tagged');
  });
  tests.forEach(test => addLines(finished, test.lines, 'tested'));

  const rawRows = [...raw.entries()].sort(([a], [b]) => a - b).map(([lengthFt, row]) => {
    const result = { lengthFt, input: row.input ?? 0, completed: row.completed ?? 0, inProgress: row.inProgress ?? 0, planned: row.planned ?? 0 };
    result.unplanned = result.input - result.completed - result.inProgress - result.planned;
    if (result.unplanned < 0) throw new DomainError('RAW_OVERDRAWN', `More ${lengthFt} ft boards are loaded or planned than were received`);
    return result;
  });
  const finishedRows = [...finished.entries()].sort(([a], [b]) => a - b).map(([lengthFt, row]) => {
    const result = { lengthFt, kilnOutput: row.kilnOutput ?? 0, recoveryIn: row.recoveryIn ?? 0, recoveryOut: row.recoveryOut ?? 0,
      tagged: row.tagged ?? 0, tested: row.tested ?? 0 };
    result.finished = result.kilnOutput - result.recoveryIn + result.recoveryOut;
    result.untagged = result.finished - result.tagged - result.tested;
    if (result.untagged < 0) throw new DomainError('FINISHED_OVERDRAWN', `More ${lengthFt} ft finished boards are cut, tagged or tested than exist`);
    return result;
  });

  const dimensions = input.nominal ? nominalDimensions(input.nominal) : null;
  const bf = ft => dimensions ? dimensions.thicknessIn * dimensions.widthIn * ft / 12 : null;
  const rawFt = field => linearFt(rawRows, field);
  const finishedFt = field => linearFt(finishedRows, field);
  const removedFt = recoverySummaries.reduce((total, item) => total + item.removedFt, 0);
  // Conservation: finished footage = kiln output footage - recovery trim loss.
  ensure(Math.abs(finishedFt('finished') - (finishedFt('kilnOutput') - removedFt)) < 1e-6, 'FOOTAGE_NOT_CONSERVED');

  return immutable({
    orderId: input.orderId,
    cycles: {
      max: input.maxCycles ?? null,
      total: cycles.length,
      completed: cycles.filter(cycle => cycle.status === 'completed').length,
      inProgress: cycles.filter(cycle => cycle.status === 'in-progress').length,
      planned: cycles.filter(cycle => cycle.status === 'planned').length,
      freeSlots: input.maxCycles == null ? null : input.maxCycles - cycles.length,
    },
    raw: rawRows,
    finished: finishedRows,
    recoveries: recoverySummaries,
    totals: {
      raw: { input: sum(rawRows, 'input'), completed: sum(rawRows, 'completed'), inProgress: sum(rawRows, 'inProgress'),
        planned: sum(rawRows, 'planned'), unplanned: sum(rawRows, 'unplanned') },
      finished: { kilnOutput: sum(finishedRows, 'kilnOutput'), finished: sum(finishedRows, 'finished'),
        tagged: sum(finishedRows, 'tagged'), tested: sum(finishedRows, 'tested'), untagged: sum(finishedRows, 'untagged') },
      linearFt: { input: rawFt('input'), completed: rawFt('completed'), unplanned: rawFt('unplanned'),
        finished: finishedFt('finished'), untagged: finishedFt('untagged'), removed: removedFt },
      boardFeet: { input: bf(rawFt('input')), completed: bf(rawFt('completed')), unplanned: bf(rawFt('unplanned')),
        finished: bf(finishedFt('finished')), tagged: bf(finishedFt('tagged')), untagged: bf(finishedFt('untagged')) },
    },
  });
}

return {computeOrderBalance};
})();

// src/domain/tag-planning.js
modules["src/domain/tag-planning.js"]=(()=>{
// Customer TAG planning (ADR-0002). Pure: plain data in, plain data out.
// Supply comes only from kiln loads:
//   READY    = completed kiln output − recovery sources + recovery pieces − YARD TAGs − TEST
//   EXPECTED = the cycle currently in the kiln (reservable, marked expected)
//   FORECAST = loads planned but not started (information only, never reservable)
// Planned stacks of ALL drafts reserve free supply. A stack assigned to a built YARD
// TAG is fulfilled by that TAG: the TAG's boards are already out of free supply, so
// they are never reserved twice, and one TAG can fulfil only one stack.
// Problems are returned as issues (error = blocking) so a screen can show them and
// a command can refuse any change that introduces a new blocking issue.

const num = value => Number(value || 0);
const positive = lines => (lines || []).filter(line => num(line.quantity) > 0);

function tagPlanningKey(lengthFt, material) { return `${num(lengthFt)}|${material || 'Material'}`; }

function planningBoardFeet(nominal, lengthFt, quantity) {
  return nominal && nominal.thicknessIn > 0 && nominal.widthIn > 0
    ? nominal.thicknessIn * nominal.widthIn * num(lengthFt) * num(quantity) / 12 : 0;
}

function tagPlanning(input) {
  const species = input.species || 'Material';
  const nominal = input.nominal || null;
  const bf = (lengthFt, quantity) => planningBoardFeet(nominal, lengthFt, quantity);
  const issues = [];
  const rows = new Map();
  const row = (lengthFt, material) => {
    const key = tagPlanningKey(lengthFt, material || species);
    if (!rows.has(key)) rows.set(key, { key, lengthFt:num(lengthFt), material:material || species,
      kilnOutput:0, recoveryIn:0, recoveryOut:0, tagged:0, tested:0, reservedReady:0, expected:0, reservedExpected:0, forecast:0 });
    return rows.get(key);
  };

  (input.kilnOutput || []).forEach(cycle => positive(cycle.lots).forEach(lot => { row(lot.lengthFt, lot.material).kilnOutput += num(lot.quantity); }));

  // A cut consumes a source length and adds shorter pieces of the same material.
  (input.recoveries || []).forEach(recovery => {
    const source = num(recovery.sourceLengthFt);
    const candidates = [...rows.values()].filter(item => item.lengthFt === source && item.kilnOutput + item.recoveryOut - item.recoveryIn > 0);
    const material = candidates.length === 1 ? candidates[0].material
      : (candidates.find(item => item.material === species) || candidates[0] || { material:species }).material;
    if (candidates.length > 1) issues.push({ level:'warning', code:'RECOVERY_MATERIAL_ASSUMED',
      message:`Recovery ${recovery.id}: ${source} ft exists in several materials; ${material} was used.` });
    row(source, material).recoveryIn += num(recovery.quantity);
    (recovery.piecesFt || []).forEach(piece => { row(piece, material).recoveryOut += num(recovery.quantity); });
  });

  const tagsById = new Map();
  const labels = new Set();
  (input.tags || []).forEach(tag => {
    if (tagsById.has(tag.id)) { issues.push({ level:'error', code:'DUPLICATE_TAG_ID', message:`TAG ${tag.label} appears twice.` }); return; }
    tagsById.set(tag.id, tag);
    const label = String(tag.label || '').trim().toLowerCase();
    if (labels.has(label)) issues.push({ level:'error', code:'DUPLICATE_TAG_LABEL', message:`TAG number ${tag.label} is used twice.` });
    labels.add(label);
    positive(tag.lines).forEach(line => { row(line.lengthFt, line.material).tagged += num(line.quantity); });
  });
  (input.tests || []).forEach(test => positive(test.lines).forEach(line => { row(line.lengthFt, line.material).tested += num(line.quantity); }));
  if (input.inProgress) positive(input.inProgress.lots).forEach(lot => { row(lot.lengthFt, lot.material).expected += num(lot.quantity); });
  (input.plannedLoads || []).forEach(load => positive(load.lots).forEach(lot => { row(lot.lengthFt, lot.material).forecast += num(lot.quantity); }));

  const linkedBy = new Map();
  const drafts = (input.drafts || []).map(draft => {
    const stacks = (draft.stacks || []).map(stack => {
      if (stack.tagId) {
        const tag = tagsById.get(stack.tagId);
        const broken = code => ({ ...stack, status:'broken', lines:[], boards:0, bf:0, code });
        if (!tag) {
          issues.push({ level:'error', code:'LINKED_TAG_MISSING', message:`${draft.customer || draft.number || 'Draft'}: stack ${stack.name} is linked to a TAG that no longer exists.` });
          return broken('LINKED_TAG_MISSING');
        }
        if (linkedBy.has(tag.id)) {
          issues.push({ level:'error', code:'TAG_LINKED_TWICE', message:`TAG ${tag.label} is assigned to two stacks.` });
          return broken('TAG_LINKED_TWICE');
        }
        linkedBy.set(tag.id, { draftId:draft.id, stackId:stack.id });
        const lines = positive(tag.lines).map(line => ({ lengthFt:num(line.lengthFt), material:line.material || species, quantity:num(line.quantity) }));
        return { ...stack, status:tag.shipped ? 'shipped' : 'tagged', tagLabel:tag.label, lines,
          boards:lines.reduce((sum, line) => sum + line.quantity, 0), bf:lines.reduce((sum, line) => sum + bf(line.lengthFt, line.quantity), 0) };
      }
      const lines = positive(stack.items).map(item => ({ id:item.id, lengthFt:num(item.lengthFt ?? item.length), material:item.material || species,
        quantity:num(item.quantity), source:item.source === 'expected' ? 'expected' : 'ready' }));
      lines.forEach(line => {
        const target = row(line.lengthFt, line.material);
        if (line.source === 'expected') target.reservedExpected += line.quantity; else target.reservedReady += line.quantity;
      });
      return { ...stack, status:'planned', lines, boards:lines.reduce((sum, line) => sum + line.quantity, 0), bf:lines.reduce((sum, line) => sum + bf(line.lengthFt, line.quantity), 0) };
    });
    const sumBf = statuses => stacks.filter(stack => statuses.includes(stack.status)).reduce((sum, stack) => sum + stack.bf, 0);
    const fulfilledBf = sumBf(['tagged', 'shipped']);
    const plannedBf = sumBf(['planned']);
    const targetBf = num(draft.targetBf);
    return { ...draft, stacks, fulfilledBf, plannedBf, totalBf:fulfilledBf + plannedBf, targetBf,
      remainingBf:targetBf > 0 ? targetBf - fulfilledBf - plannedBf : null };
  });

  const result = [...rows.values()].sort((a, b) => a.lengthFt - b.lengthFt || a.material.localeCompare(b.material)).map(item => {
    const finished = item.kilnOutput - item.recoveryIn + item.recoveryOut;
    const loose = finished - item.tagged - item.tested;
    const freeReady = loose - item.reservedReady;
    const freeExpected = item.expected - item.reservedExpected;
    const where = `${item.lengthFt} ft ${item.material}`;
    if (finished < 0 || loose < 0) issues.push({ level:'error', code:'FINISHED_OVERDRAWN', message:`${where}: more boards are cut, tagged or tested than were produced.` });
    if (freeReady < 0) issues.push({ level:'error', code:'READY_OVERBOOKED', message:`${where}: ${-freeReady} boards more are planned than are free in the warehouse.` });
    if (freeExpected < 0) issues.push({ level:'error', code:'EXPECTED_OVERBOOKED', message:`${where}: ${-freeExpected} boards more are planned than the kiln cycle holds.` });
    return { ...item, finished, loose, freeReady, freeExpected,
      freeReadyBf:bf(item.lengthFt, Math.max(0, freeReady)), freeExpectedBf:bf(item.lengthFt, Math.max(0, freeExpected)) };
  });
  const tags = [...tagsById.values()].map(tag => ({ id:tag.id, label:tag.label, shipped:Boolean(tag.shipped),
    boards:positive(tag.lines).reduce((sum, line) => sum + num(line.quantity), 0),
    bf:positive(tag.lines).reduce((sum, line) => sum + bf(line.lengthFt, line.quantity), 0),
    lines:positive(tag.lines), assignment:linkedBy.get(tag.id) || null }));
  const total = field => result.reduce((sum, item) => sum + item[field], 0);
  return {
    rows:result, tags, drafts, issues,
    blocking:issues.filter(issue => issue.level === 'error').map(issue => `${issue.code}:${issue.message}`),
    totals:{ finished:total('finished'), tagged:total('tagged'), tested:total('tested'), loose:total('loose'),
      reservedReady:total('reservedReady'), freeReady:total('freeReady'), expected:total('expected'),
      reservedExpected:total('reservedExpected'), freeExpected:total('freeExpected'), forecast:total('forecast') },
  };
}

// Command guard shared by every screen: a change is accepted only if it introduces
// no blocking issue that the current state did not already have.
function checkPlanningChange(input, currentDrafts, nextDrafts) {
  const current = tagPlanning({ ...input, drafts:currentDrafts });
  const proposed = tagPlanning({ ...input, drafts:nextDrafts });
  const introduced = proposed.blocking.filter(issue => !current.blocking.includes(issue));
  return { accepted:introduced.length === 0, introduced, plan:proposed };
}

return {tagPlanningKey,planningBoardFeet,tagPlanning,checkPlanningChange};
})();

// src/adapters/legacy-tag-planning.js
modules["src/adapters/legacy-tag-planning.js"]=(()=>{
// Legacy browser-storage records → Domain inputs for order balance and TAG planning.
// Read-only: it never writes. Record selection matches the legacy warehouse screen
// (same order match, same completed-cycle merge) so every screen counts the same
// boards. `getItem` is the browser storage getter or a snapshot lookup.
const LEGACY_KEYS = Object.freeze({
  active:'kiln-planner-active-order-v1', orderPrefix:'kiln-planner-order-v1:',
  completed:'kiln-planner-completed-cycles-v1', tags:'kiln-planner-shipping-tags-v1',
  shipments:'kiln-planner-shipments-v1', recovery:'kiln-planner-recovery-operations-v1',
  tests:'kiln-planner-test-boards-v1', preorders:'kiln-planner-preliminary-orders-v1',
});
const num = value => Number(value || 0);
function readJson(getItem, key, fallback) {
  try { const raw = getItem(key); return raw == null ? fallback : JSON.parse(raw); } catch (_) { return fallback; }
}
function readList(getItem, key) { const value = readJson(getItem, key, []); return Array.isArray(value) ? value : []; }

function legacyActiveOrder(getItem) {
  const pointer = readJson(getItem, LEGACY_KEYS.active, null);
  if (!pointer?.orderRef) return pointer;
  return readJson(getItem, LEGACY_KEYS.orderPrefix + pointer.orderRef, null);
}
function legacyBelongsToOrder(item, order) {
  return !order || item.orderId === order.id || item.orderId === order.planSignature
    || item.productionOrderNumber === order.number || item.orderNumber === order.number;
}
function completedFor(getItem, order) {
  const merged = new Map();
  const ledger = readList(getItem, LEGACY_KEYS.completed).filter(item => legacyBelongsToOrder(item, order));
  const embedded = Array.isArray(order?.completedCycles) ? order.completedCycles : [];
  [...embedded, ...ledger].forEach((record, index) => {
    const key = record?.id || `${record?.orderId || record?.orderNumber || 'order'}::load-${record?.loadNumber || index}`;
    merged.set(key, record);
  });
  return [...merged.values()].sort((a, b) => String(a.completedDate).localeCompare(String(b.completedDate)) || a.loadNumber - b.loadNumber);
}
function nominalFor(order) {
  const raw = String(order?.inputs?.size || '');
  const values = raw === 'custom' ? [] : (raw.match(/[\d.]+/g) || []).map(Number);
  const thicknessIn = values[0] || num(order?.inputs?.customT);
  const widthIn = values[1] || num(order?.inputs?.customW);
  return thicknessIn > 0 && widthIn > 0 ? { thicknessIn, widthIn } : null;
}
const toLines = (quantities, material) => Object.entries(quantities || {})
  .map(([length, quantity]) => ({ lengthFt:num(length), material, quantity:num(quantity) }))
  .filter(line => line.quantity > 0);
// Confirmed quantities win; quality lots only split them by material.
function cycleLots(record, species) {
  const lots = Array.isArray(record?.qualityLots) ? record.qualityLots : [];
  return Object.entries(record?.quantities || {}).flatMap(([rawLength, rawQuantity]) => {
    const lengthFt = num(rawLength);
    let remaining = Math.max(0, num(rawQuantity));
    const result = [];
    lots.filter(lot => num(lot.length) === lengthFt && num(lot.quantity) > 0).forEach(lot => {
      const quantity = Math.min(remaining, num(lot.quantity));
      const material = lot.material && !/UNASSIGNED/i.test(lot.material) ? lot.material : species;
      if (quantity > 0) result.push({ lengthFt, material, quantity });
      remaining -= quantity;
    });
    if (remaining > 0) result.push({ lengthFt, material:record?.species || species, quantity:remaining });
    return result;
  });
}

function loadLegacyOrder(getItem) {
  const order = legacyActiveOrder(getItem);
  if (!order) return null;
  const species = order.inputs?.species || 'Material';
  const cycles = completedFor(getItem, order);
  const cycleIds = new Set(cycles.map(item => item.id));
  const tags = readList(getItem, LEGACY_KEYS.tags).filter(tag => legacyBelongsToOrder(tag, order) || (tag.sourceLoads || []).some(source => cycleIds.has(source.id)));
  const tagIds = new Set(tags.map(tag => tag.id));
  const shipments = readList(getItem, LEGACY_KEYS.shipments).filter(item => legacyBelongsToOrder(item, order) || (item.tagIds || []).some(id => tagIds.has(id)));
  const shippedTagIds = new Set(shipments.flatMap(shipment => shipment.tagIds || []));
  const recoveries = readList(getItem, LEGACY_KEYS.recovery).filter(item => legacyBelongsToOrder(item, order));
  const tests = readList(getItem, LEGACY_KEYS.tests).filter(item => legacyBelongsToOrder(item, order));
  const allDrafts = readList(getItem, LEGACY_KEYS.preorders);
  const plans = (() => { const raw = order.viewCache?.plans; try { return typeof raw === 'string' ? JSON.parse(raw) : raw || []; } catch (_) { return []; } })();
  const records = Array.isArray(order.viewCache?.records) ? order.viewCache.records : [];
  const completedNumbers = new Set(cycles.map(record => num(record.loadNumber)));
  const activeNumber = num(order.activeCycleNumber);
  const unmap = value => (value && value.__kilnMap ? Object.fromEntries(value.__kilnMap) : value || {});
  const inProgressRecord = activeNumber && !completedNumbers.has(activeNumber) ? records.find(item => num(item.number) === activeNumber) : null;
  const plannedLoads = plans.map((plan, index) => ({ loadNumber:index + 1, plan }))
    .filter(({ loadNumber }) => !completedNumbers.has(loadNumber) && loadNumber !== activeNumber)
    .map(({ loadNumber, plan }) => ({ loadNumber, lots:toLines(unmap(plan.usedMap), species) }));
  const nominal = nominalFor(order);
  const planning = {
    orderId:order.id, species, nominal,
    kilnOutput:cycles.map(record => ({ cycleId:record.id, loadNumber:num(record.loadNumber), lots:cycleLots(record, species) })),
    inProgress:inProgressRecord ? { loadNumber:activeNumber, lots:toLines(inProgressRecord.used, species) } : null,
    plannedLoads,
    recoveries:recoveries.map(item => ({ id:item.id, sourceLengthFt:num(item.sourceLength), quantity:num(item.quantity), piecesFt:(item.outputs || []).map(num) })),
    tags:tags.map(tag => ({ id:tag.id, label:String(tag.tag || ''), lines:toLines(tag.quantities || tag.directQuantities, tag.material || species), shipped:shippedTagIds.has(tag.id), date:tag.date || '' })),
    tests:tests.map(test => ({ id:test.id, lines:toLines(test.quantities || { [test.length]:test.quantity }, test.material || species) })),
    drafts:allDrafts.filter(draft => draft.orderId === order.id),
  };
  const balance = {
    orderId:order.id, nominal, maxCycles:num(order.plannedCycles) || null,
    receipts:[{ id:`receipt:${order.id}`, lines:toLines(order.calculatedInventory || order.inventory, species) }],
    cycles:[
      ...cycles.map(record => ({ id:record.id, number:num(record.loadNumber), status:'completed', lines:toLines(record.quantities, species) })),
      ...(inProgressRecord ? [{ id:`active:${activeNumber}`, number:activeNumber, status:'in-progress', lines:toLines(inProgressRecord.used, species) }] : []),
      ...plannedLoads.map(load => ({ id:`plan:${load.loadNumber}`, number:load.loadNumber, status:'planned', lines:load.lots })),
    ],
    recoveries:planning.recoveries,
    tags:planning.tags.map(tag => ({ id:tag.id, label:tag.label, lines:tag.lines })),
    tests:planning.tests,
  };
  return { order, species, planning, balance, allDrafts };
}

// Legacy drafts → planner format. A stack is linked to a built TAG only when its name
// equals the TAG number of the same order AND its per-length counts equal the TAG
// exactly; nothing is linked by guesswork. Idempotent.
function migrateLegacyDrafts(drafts, tags) {
  const positive = lines => (lines || []).filter(line => num(line.quantity) > 0);
  const byLabel = new Map(tags.map(tag => [String(tag.label || '').trim().toLowerCase(), tag]));
  const perLength = lines => JSON.stringify(Object.entries(positive(lines).reduce((acc, line) => {
    const length = num(line.lengthFt ?? line.length); acc[length] = (acc[length] || 0) + num(line.quantity); return acc;
  }, {})).sort(([a], [b]) => a - b));
  const linked = new Set();
  drafts.forEach(draft => (draft.stacks || []).forEach(stack => { if (stack.tagId) linked.add(stack.tagId); }));
  let changed = false;
  const next = drafts.map(draft => ({ ...draft, stacks:(draft.stacks || []).map(stack => {
    const items = (stack.items || []).map(item => (item.lengthFt != null ? item : {
      id:item.id, lengthFt:num(item.length), material:item.material, quantity:num(item.quantity),
      source:item.sourceStatus === 'expected' ? 'expected' : 'ready', legacyLotId:item.lotId || null,
    }));
    if (items.some((item, index) => item !== (stack.items || [])[index])) changed = true;
    if (stack.tagId) return { ...stack, items };
    const tag = byLabel.get(String(stack.name || '').trim().toLowerCase());
    if (tag && !linked.has(tag.id) && perLength(tag.lines) === perLength(items)) {
      linked.add(tag.id);
      changed = true;
      return { ...stack, items, tagId:tag.id, linkedAt:'migration' };
    }
    return { ...stack, items };
  }) }));
  return { drafts:next, changed };
}

return {LEGACY_KEYS,legacyActiveOrder,legacyBelongsToOrder,loadLegacyOrder,migrateLegacyDrafts};
})();

// src/bundles/kiln-core.js
modules["src/bundles/kiln-core.js"]=(()=>{
// Entry for dist/kiln-core.js — the single source of production rules used by the
// live kiln-load-planner-web screens (ADR-0003). Only pure Domain modules and the
// read-only legacy adapter are included; no storage, network or UI code.
const { computeOrderBalance }=modules["src/domain/order-balance.js"];
const { tagPlanning, checkPlanningChange, planningBoardFeet, tagPlanningKey }=modules["src/domain/tag-planning.js"];
const { DomainError }=modules["src/domain/shared.js"];
const { LEGACY_KEYS, loadLegacyOrder, legacyActiveOrder, legacyBelongsToOrder, migrateLegacyDrafts }=modules["src/adapters/legacy-tag-planning.js"];

const KilnCore = Object.freeze({
  CoreError:DomainError, orderBalance:computeOrderBalance, tagPlanning, checkPlanningChange,
  migrateLegacyDrafts, boardFeet:planningBoardFeet, lotKey:tagPlanningKey,
});
const KilnLegacy = Object.freeze({
  KEYS:LEGACY_KEYS, load:loadLegacyOrder, activeOrder:legacyActiveOrder, belongsToOrder:legacyBelongsToOrder,
});

return {KilnCore,KilnLegacy};
})();
globalThis.KilnCore=modules["src/bundles/kiln-core.js"].KilnCore;
globalThis.KilnLegacy=modules["src/bundles/kiln-core.js"].KilnLegacy;
})();
